# Generated by Django 5.2.12 on 2026-03-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='vaultentry',
            name='credential_type',
            field=models.CharField(choices=[('password', 'Password'), ('api_key', 'API Key'), ('token', 'Token'), ('secret', 'Secret'), ('other', 'Other')], default='password', max_length=50),
        ),
        migrations.AddField(
            model_name='vaultentry',
            name='name',
            field=models.CharField(default='Unnamed Credential', max_length=255),
        ),
        migrations.AlterField(
            model_name='vaultentry',
            name='email_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='vaultentry',
            name='password_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
    ]
